name: Process and Publish Binaries

# Triggers: runs after "llvm" workflow completes; also allows manual trigger (requires run_id)
on:
  workflow_run:
    workflows: ["llvm"]
    types:
      - completed
  pull_request:
    branches: [main-test]

jobs:
  process-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2025
          - os: ubuntu-24.04
          - os: macos-15

    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4

      - name: Upload LLVM
        env:
          RUN_ID: 20195540140
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/upload-llvm.py
